Repository elementary/switchboard-plug-sound, pull requests merged in 2021-11, with the labels that each got.

#210 Expose Screen Reader settings in Audio
  src/OutputPanel.vala
Labels: Needs Design

#212 Remove redundant panel titles
  src/InputPanel.vala
  src/OutputPanel.vala
Labels: Bitesize

#214 Release 2.3.0
  data/sound.appdata.xml.in
  meson.build
Labels: Release
